---
- name: Update repository chache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Setup timezone
  timezone:
    name: "{{app_timezone}}"

- name: Install most common applications
  apt:
    name: git, htop, rsync, nano, mc
    state: present

- name: Set nano to default text editor
  lineinfile:
    path: ~/.bashrc
    regexp: "^export EDITOR"
    line: "export EDITOR=nano"
