# Use postgres/example user/password credentials
version: "3.1"

services:
  postgres:
    container_name: marketplace_postgresql
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - jd2_marketplace_postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: marketplace_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@postgres.org"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    volumes:
      - jd2_marketplace_pgadmin:/var/lib/pgadmin
    ports:
      - "8081:80"

volumes:
  jd2_marketplace_postgresql:
  jd2_marketplace_pgadmin:
