---
- name: Dump Database
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Dump Database
    shell: docker exec -i "{{ lookup('env','ANSIBLE_DOCKER_POSTGRESQL_CONTAINER') }}" pg_dump -U postgres "{{ lookup('env','ANSIBLE_DATABASE_NAME') }}" > ../assets/backups/"{{ lookup('env','ANSIBLE_DATABASE_NAME') }}".sql
    ignore_errors: yes
